"""Add Body Type

Revision ID: 63b61968ddd6
Revises: 628872ee5d55
Create Date: 2024-07-28 21:11:47.359707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63b61968ddd6'
down_revision = '628872ee5d55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body_type', sa.Enum('MARKDOWN', 'HTML', 'TEXT', name='bodytype'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('body_type')

    # ### end Alembic commands ###
