"""Extend comments

Revision ID: ff3fecb8490c
Revises: fbaa0dfd3540
Create Date: 2024-08-02 22:17:42.843936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff3fecb8490c'
down_revision = 'fbaa0dfd3540'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('disabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('post_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_comments_timestamp'), ['timestamp'], unique=False)
        batch_op.create_foreign_key('fk_comments_posts', 'posts', ['post_id'], ['id'])
        batch_op.create_foreign_key('fk_comments_users', 'users', ['author_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_comments_posts', type_='foreignkey')
        batch_op.drop_constraint('fk_comments_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_comments_timestamp'))
        batch_op.drop_column('post_id')
        batch_op.drop_column('author_id')
        batch_op.drop_column('disabled')
        batch_op.drop_column('timestamp')
        batch_op.drop_column('body')

    # ### end Alembic commands ###
